%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/gt/src/AnalogSeismicNetworkPaper/hypocenters_duplicates_removed.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/02/20 02:20:29

%% Initialize variables.
filename = '/Users/gt/src/AnalogSeismicNetworkPaper/hypocenters_duplicates_removed.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%q)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%q%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
tbl = table(dataArray{1:end-1}, 'VariableNames', {'index','otime','lat','lon','depth','mag'});

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% added by glenn
close all
cobj=Catalog(datenum(tbl.otime), tbl.lon, tbl.lat, tbl.depth, tbl.mag)
cobj.plot_time()
cobj.plot()
open contourmap_ASN_sites.fig
j = jet(255);
c=1+round(254*(cobj.otime - min(cobj.otime))/(max(cobj.otime)-min(cobj.otime)) )
scatter(-cobj.lon, cobj.lat, 20*(cobj.mag+1.5), j(c,:))
saveas(gcf,'asn_epicenters.eps','epsc')
saveas(9,'asn_depthmag_vs_time.eps','epsc')
saveas(2,'asn_depthmag_vs_time.eps','epsc')
saveas(2,'asn_depthmag_vs_time.pdf','pdf')
saveas(9,'asn_epicenters.pdf','pdf')